name = "GraphicsMath"
uuid = "c7a8a04f-9555-4fea-9aa6-9f2fbff5049a"
authors = ["Michael Fiano <mail@mfiano.net> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.7"
Reexport = "1"
StaticArrays = "1.5"
